spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salesdata?serverTimezone=UTC
    username: root
    password: MyNewPass
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: demo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8080
  servlet:
    context-path: /vinni-demo